### ISSUE TITLE
gnote support

### ISSUE THREAD

**Issue by lelutin** [lelutin/scout#19]
As long as gnote aims to be a 1:1 port of Tomboy notes, it would be very nice to offer support for interfacing with gnote as well.
- Is gnote using the same DBus interface (functions) as Tomboy? -- **yes**
- Is the interface versioned like Tomboy's one? (this way, it would be easier to identify sets of missing features for older "protocols"). -- **yes**
- What is the dbus object name that we need to get? -- **org.gnome.Gnote.RemoteControl**
- How could gnote support be implemented in a clean way. That is, how do we tell tomtom which one of Tomboy and gnote we are using? (configuration file? command-line option? enviroment variable?)

**Comment by yupthatguy** [comment]
I have a rather odd situation. It doesn't matter if it is a previously saved note or a new note, while I am editing a note, if I switch active windows in Ubuntu 18.04, Gnote will delete the most recent information that I typed into the note. I am using Gnote 3.28.0. As you can imagine, this gets annoying quickly.. any thoughts on how to fix this super annoying bug?
